website_list = [
    {"url": "https://greatminds.recruitee.com/?jobs-c88dea0d%5Btab%5D=all",
     "name": "Great Minds", 
     "scraper": scrape_greatMinds}
    # {"url": "https://www.prometheanworld.com/about-us/careers/", 
    #  "name": "Promethean", 
    #  "scraper": scrape_promethean},
    # {"url": "https://www.masteryprep.com/join-team/#Openings",
    #  "name": "MasteryPrep",
    #  "scraper": scrape_masteryprep,
    # NOT ACTUALLY PULLING TEXT FROM WEB ELEMENT FOR SOME REASON},
    # {"url": "https://recruiting.ultipro.com/HOL1002HPHM/JobBoard/be27b89b-3cb9-491f-a1b0-42f8b077a9dd/?q=&o=postedDateDesc&w=&wc=&we=&wpst=&f4=P3uiKTJuwU-EMui9Ye7png&f5=Z6VUAqvr8UOWHe2Wz3tZ7w",
    #  "name": "Macmillan Learning",
    #  "scraper": scrape_macmillan},
    # {"url": "https://job-boards.greenhouse.io/newsela",
    #  "name": "Newsela",
    #  "scraper": scrape_newsela},
    # {"url": "https://jobs.dayforcehcm.com/en-US/k12l/CANDIDATEPORTAL",
    #  "name": "Savvas",
    #  "scraper": scrape_savvas},
    # {"url": "https://job-boards.greenhouse.io/edmentum",
    #  "name": "Edmentum",
    #  "scraper": scrape_edmentum},
    # {"url": "https://careers.coursera.com/jobs/search?page=1&query=&department_uids%5B%5D=0b370cc4e5d8b1fba08d06720b9850aa&country_codes%5B%5D=US",
    #  "name": "Coursera",
    #  "scraper": scrape_coursera},
    # {"url": "https://job-boards.greenhouse.io/goguardian",
    #  "name": "GoGuardian/Peardeck",
    #  "scraper": scrape_goguardian},
    # {"url": "https://careers.smartrecruiters.com/Skyward1",
    #  "name": "Skyward", 
    #  "scraper": scrape_skyward},
    # {"url": "https://pearson.jobs/locations/usa/schedule/full-time/workplace-type/remote/jobs/",
    #  "name": "Pearson",
    #  "scraper": scrape_pearson},
    # {"url": "https://www.powerschool.com/company/careers/?location=US--Remote",
    #  "name": "Powerschool",
    #  "scraper": scrape_powerschool},
    # {"url": "https://www.khanacademy.org/careers#openings", 
    #  "name": "Khan Academy",
    #  "scraper": scrape_khan},
    # {"url": "https://jobs.abre.com/",
    #  "name": "Abre",
    #  "scraper": scrape_abre},
    # {"url": "https://proxlearn.bamboohr.com/careers",
    #  "name": "Proximity Learning",
    #  "scraper": scrape_proximity_learning},
    # {"url": "https://www.governmentjobs.com/careers/colorado?location[0]=denver%20metro&department[0]=Department%20of%20Education&sort=PositionTitle%7CAscending",
    #  "name": "Colorado Dept of Ed",
    #  "scraper": scrape_coloradodoe},
    # {"url": "https://edtechjobs.io",
    #   "name": "Edtechjobs.io",
    #   "scraper": scrape_edtechjobsio},
    # {"url": "https://www.deltamath.com/jobs/",
    #  "name": "DeltaMath",
    #  "scraper": scrape_deltamath},
    # {"url": "https://jobs.cambiumlearning.com/?size=n_50_n",
    # "name": "Cambium Learning Group",
    # "scraper": scrape_cambium},
    # {"url": "https://jobs.ashbyhq.com/magicschool/",
    # "name": "Magic School",
    # "scraper": scrape_magicschool},
    # {"url": "https://www.pairin.com/about/careers/",
    #  "name": "Pairin",
    #  "scraper": scrape_pairin,
    # },
    # {"url": "https://careers.jeffco.k12.co.us/psc/careers/EMPLOYEE/APPLICANT/c/HRS_HRAM_FL.HRS_CG_SEARCH_FL.GBL?FOCUS=Applicant&SiteId=3",
    #  "name": "JeffCo Schools", 
    #  "scraper": scrape_jeffco_schools},
    # {"url": "https://dpsjobboard.dpsk12.org/en/sites/CX_1001/jobs?lastSelectedFacet=TITLES&mode=location&selectedTitlesFacet=30%3B46",
    #  "name": "Denver Public Schools",
    #  "scraper": scrape_dps_aurora},
    # {"url": "https://dcsd.wd5.myworkdayjobs.com/en-US/DCSD/details/Systems-Engineer-II_Req-00077984-2?timeType=f5213912a3b710211de745c6879eb635&jobFamily=fef6e4a613001022976a2e0edb5b3686&jobFamily=fef6e4a613001022976a2c4522c13684",
    #  "name": "DCSD",
    #  "scraper": scrape_public_schools_workday},
    # {"url": "https://fa-epop-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs?lastSelectedFacet=CATEGORIES&selectedCategoriesFacet=300000024830845",
    #  "name": "Aurora Schools",
    #  "scraper": scrape_dps_aurora},
    # {"url": "https://dsstpublicschools.wd5.myworkdayjobs.com/DSST_Careers?jobFamily=a62b5af9bc7b100114066481a8960000&jobFamily=d969b57881e70103beb07a72d629da6b&jobFamily=d969b57881e70104991d7a72d629d86b",
    #  "name": "DSST System",
    #  "scraper": scrape_public_schools_workday}, 
]
